USE attendance_system;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  recipient_id BIGINT UNSIGNED NOT NULL,
  type ENUM('ATTENDANCE_APPROVED', 'ATTENDANCE_REJECTED', 'ATTENDANCE_DELETED', 'SYSTEM_ANNOUNCEMENT') NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  date_info VARCHAR(120) NULL,
  reason VARCHAR(500) NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notifications_recipient (recipient_id, is_read, created_at),
  CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
