ALTER TABLE notifications
  MODIFY COLUMN type ENUM(
    'ATTENDANCE_APPROVED',
    'ATTENDANCE_REJECTED',
    'ATTENDANCE_DELETED',
    'SYSTEM_ANNOUNCEMENT',
    'ATTENDANCE_REQUEST',
    'FACE_REGISTRATION_REQUEST'
  ) NOT NULL;
